// Writes src/environments/environment.prod.ts from the API_URL env var at
// build time. Used by static-site hosts (e.g. Render) where the Angular app
// is built with `npm run build:render` and talks to the backend directly.
//
//   API_URL="https://my-backend.onrender.com"  ->  apiUrl: 'https://my-backend.onrender.com'
//   (unset / empty)                            ->  apiUrl: ''  (same-origin)
const fs = require('fs');
const path = require('path');

const apiUrl = (process.env.API_URL || '').replace(/\/+$/, ''); // strip trailing slash
const target = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');

const contents = `// AUTO-GENERATED by set-env.js at build time. Do not edit by hand.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

fs.writeFileSync(target, contents, 'utf8');
console.log(`[set-env] wrote environment.prod.ts with apiUrl='${apiUrl}'`);
